### ISSUE TITLE
Please change the faker value look like $this->faker->bothify(' Code ?###?')

### ISSUE THREAD

**Issue by nhungredweb** [PhamHanh96/Hanh_Project_Intern_Codeception#1]
https://github.com/PhamHanh96/Hanh_Project_Intern_Codeception/blob/1f68284fa26543b8e3b4e47dec37e149be68c617/tests/acceptance/Admin/BusCest.php#L13

**Comment by PhamHanh96** [comment]
what is this mean? I don't understand your mind :(

**Comment by PhamHanh96** [comment]
I done. Thank you :D
