### ISSUE TITLE
Please remove  $I->pauseExecution(); here

### ISSUE THREAD

**Issue by nhungredweb** [PhamHanh96/Hanh_Project_Intern_Codeception#4]
https://github.com/PhamHanh96/Hanh_Project_Intern_Codeception/blob/1f68284fa26543b8e3b4e47dec37e149be68c617/tests/acceptance/User/UserBookTicketCest.php#L38

**Comment by PhamHanh96** [comment]
I done :D

**Comment by nhungredweb** [comment]
thanks
