### ISSUE TITLE
Please review all the code again and make sure don't have any  $I->pauseExecution(); on the project 

### ISSUE THREAD

**Issue by nhungredweb** [PhamHanh96/Hanh_Project_Intern_Codeception#5]
https://github.com/PhamHanh96/Hanh_Project_Intern_Codeception/blob/1f68284fa26543b8e3b4e47dec37e149be68c617/tests/acceptance/User/UserInforemationCest.php#L29

**Comment by PhamHanh96** [comment]
I done :D
